issue_tracker/issue_tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from webapp.views import ProjectView, CreateProjectView, ProjectDetailView, UpdateProjectView, DeleteProjectView, \
    IssueListView, IssueView, CreateIssueView, UpdateIssueView, DeleteIssueView \


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
]

issue_tracker/webapp/urls.py
from django.urls import path
from webapp.views import ProjectView, CreateProjectView, ProjectDetailView, UpdateProjectView, DeleteProjectView, \
    IssueListView, IssueView, CreateIssueView, UpdateIssueView, DeleteIssueView \

app_name = 'webapp'

urlpatterns = [
    # Project urls
    path('', ProjectView.as_view(), name='project_list'),
    path('project/create/', CreateProjectView.as_view(), name='create_project'),
    path('project/detail/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/update/<int:pk>/', UpdateProjectView.as_view(), name='update_project'),
    path('project/delete/<int:pk>/', DeleteProjectView.as_view(), name='delete_project'),

    # Issue urls
    path('issue/list/', IssueListView.as_view(), name='issue_list'),
    path('issue/detail/<int:pk>/', IssueView.as_view(), name='issue_detail'),
    path('issue/create/<int:pk>', CreateIssueView.as_view(), name='create_issue'),
    path('issue/update/<int:pk>/', UpdateIssueView.as_view(), name='update_issue'),
    path('issue/delete/<int:pk>/', DeleteIssueView.as_view(), name='delete_issue'),
]

issue_tracker/webapp/models.py
from django.db import models
from django.urls import reverse

from webapp.validate import not_only_numeric


# Create your models here.
class Project(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    title = models.CharField(max_length=300, null=False, blank=False, verbose_name='Title', validators=(not_only_numeric,))
    description = models.TextField(max_length=300, null=True, blank=True, verbose_name='Description')

    def get_absolute_url(self):
        return reverse('webapp:project_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.pk}. {self.title}'


class Issue(models.Model):
    summary = models.CharField(max_length=300, null=False, blank=False, verbose_name='Summary', validators=(not_only_numeric,))
    description = models.TextField(max_length=300, null=True, blank=True, verbose_name='Description')
    type = models.ManyToManyField('webapp.Type', related_name='issues', blank=True)
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT, related_name='status', verbose_name='Status')
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, related_name='issues', verbose_name='projects')
    is_deleted = models.BooleanField(default=False)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Update At')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Created At')

    def get_absolute_url(self):
        return reverse('webapp:issue_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return f'{self.pk}. {self.summary}'


class Status(models.Model):
    status_name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Status')

    def __str__(self):
        return f'{self.status_name}'


class Type(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False, verbose_name='Type')

    def __str__(self):
        return f'{self.name}'

issue_tracker/webapp/forms.py
from django import forms
from django.forms import widgets, ValidationError
from webapp.models import Type, Status, Issue, Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['start_date', 'end_date',  'title', 'description']
        # exclude = []

        widgets = {
            'start_date': forms.DateInput(attrs={'class': 'form-control'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }

        error_messages = {
            'content': {
                'required': 'Field is required'
            }
        }


class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['summary', 'description',  'type', 'status']
        # exclude = []

        widgets = {
            'summary': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'type': widgets.CheckboxSelectMultiple,
            'status': forms.Select(attrs={'class': 'form-control'})
        }

        error_messages = {
            'content': {
                'required': 'Field is required'
            }
        }


    def clean_summary(self):
        summary = self.cleaned_data['summary']
        if len(summary) > 20:
            self.add_error('summary', ValidationError('Length should be no more than %(length)d characters!',
                                                    code='too_short', params={'length': 20}))
        return summary

    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) > 3000:
            self.add_error('summary', ValidationError('Длина зтого поля должна составлять не меенее %(length)d символов!',
                                                    code='too_short', params={'length': 3000}))
        return description

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['summary'] == cleaned_data.get('content', ''):
            raise ValidationError('Текст статьи не должен дублировать ее название!')
        return cleaned_data

class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False)

issue_tracker/webapp/views/base_views.py
from django.shortcuts import render, redirect
from django.views.generic import View, TemplateView, ListView


class CustomCreateView(View):
    form_class = None
    template_name = None
    model = None
    redirect_url = None

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = {'form': form}
        return render(self.request, self.template_name, context)

    def get_redirect_url(self):
        return self.redirect_url


class CustomSearchView(ListView):
    search_form = None

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return self.search_form(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_query(self):
        queryset = super().get_queryset()
        if self.search_value:
            pass
        return queryset


class CustomListView(TemplateView):
    model = None
    context_key = 'objects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_objects()
        return context

    def get_objects(self):
        return self.model.objects.all()


class CustomFormView(View):
    template_name = None
    form_class = None
    redirect_url = ''

    def get_context_data(self, **kwargs):
        return kwargs

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        context = self.get_context_data(form=form)
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_redirect_url(self):
        return self.redirect_url

    def form_valid(self, form):
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        return render(self.request, self.template_name, context)

issue_tracker/webapp/views/issue_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils.http import urlencode
from webapp.models import Issue, Project
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.forms import IssueForm, SearchForm
from webapp.views.base_views import CustomSearchView


class IssueListView(ListView):
    template_name = 'issues/list.html'
    model = Issue
    context_object_name = 'issues'
    ordering = ('-created_at')
    paginate_by = 3
    paginate_orphans = 2

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_deleted=False)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = SearchForm
        return context


class SearchView(CustomSearchView):

    template_name = 'issues/list.html'
    model = Issue
    search_form = SearchForm
    context_object_name = 'issues'
    ordering = ('-created_at')
    paginate_by = 3
    paginate_orphans = 2

    def get_queryset(self):
        if self.search_value:
            queryset = super().get_queryset()
            queryset = queryset.filter(Q(summary__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class IssueView(DetailView):
    template_name = 'issues/detail.html'
    model = Issue


class CreateIssueView(LoginRequiredMixin, CreateView):
    template_name = "issues/create.html"
    model = Issue
    form_class = IssueForm

    def form_valid(self, form):
        project = (get_object_or_404(Project, pk=self.kwargs.get('pk')))
        issue = form.save(commit=False)
        issue.project = project
        issue.save()
        return redirect('project_detail', pk=project.pk)


class UpdateIssueView(LoginRequiredMixin, UpdateView):
    template_name = 'issues/update.html'
    form_class = IssueForm
    model = Issue
    context_object_name = 'issue'


class DeleteIssueView(LoginRequiredMixin, DeleteView):
    template_name = 'issues/delete.html'
    model = Issue
    context_object_name = 'issue'
    success_url = reverse_lazy('project_list')

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.is_deleted = True
        self.object.save()
        return HttpResponseRedirect(success_url)

issue_tracker/webapp/views/project_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic.list import MultipleObjectMixin
from django.utils.http import urlencode
from webapp.models import Project
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.forms import ProjectForm, SearchForm


class ProjectView(ListView):
    template_name = 'projects/list.html'
    model = Project
    context_object_name = 'projects'
    paginate_by = 3
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(Q(title__icontains=self.search_value) | Q(description__icontains=self.search_value))
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search'] = self.search_value
        return context


class ProjectDetailView(DetailView, MultipleObjectMixin):
    template_name = 'projects/detail.html'
    model = Project
    paginate_by = 3
    # context_object_name = 'issues'

    def get_context_data(self, **kwargs):
        project = self.object
        issues = project.issues.filter(is_deleted=False).order_by('-created_at')
        context = super(ProjectDetailView, self).get_context_data(object_list=issues, **kwargs)
        return context


class CreateProjectView(LoginRequiredMixin, CreateView):
    template_name = "projects/create.html"
    model = Project
    form_class = ProjectForm


class UpdateProjectView(LoginRequiredMixin, UpdateView):
    template_name = 'projects/update.html'
    form_class = ProjectForm
    model = Project
    context_object_name = 'project'


class DeleteProjectView(LoginRequiredMixin, DeleteView):
    template_name = 'projects/delete.html'
    model = Project
    context_object_name = 'project'
    success_url = reverse_lazy('project_list')

issue_tracker/webapp/templates/partial/form.html
{% csrf_token %}

{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

{% for field in form %}
    <p><label for="{{ field.id_for_label }}">{{ field.label }}</label></p>
    {% for error in field.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    <p>{{ field }}</p>
{% endfor %}



<input type="submit" value="{{ button_name }}">

issue_tracker/webapp/templates/partial/issue_card.html
<div class="card" style="width: 18rem;">
      <div class="card-body">
          <h5 class="card-title">{{ issue.summary }} </h5>
          <h6 class="card-subtitle mb-2 text-muted"><i>Status: </i> {{ issue.status.status_name }}</h6>
          <h6 class="card-subtitle mb-2 text-muted"><i>Type:</i>
              {% for type in issue.type.all %}
              {{ type.name }}
              {% if not forloop.last %}, {% endif %}
              {% endfor %}
          </h6>
          <p class="card-text">{{ issue.description|linebreaks }}</p>
          {% if request.user.is_authenticated %}
          <a href="{% url 'webapp:update_issue' issue.pk %}" class="card-link"><i class="fa-solid fa-pen-to-square"></i></a>
          <a href="{% url 'webapp:delete_issue' issue.pk %}" class="card-link"><i class="fa-solid fa-trash"></i></a>
          {% endif %}
      </div>
    </div>
    <p></p>

issue_tracker/webapp/templates/partial/issue_cards.html
<div class="card" style="width: 18rem;">
      <div class="card-body">
          <h5 class="card-title">{{ issue.summary }} </h5>
          <h6 class="card-subtitle mb-2 text-muted"><i>Status: </i> {{ issue.status.status_name }}</h6>
          <h6 class="card-subtitle mb-2 text-muted"><i>Type:</i>
           {% for type in issue.type.all %}
              {{ type.name }}
              {% if not forloop.last %}, {% endif %}
              {% endfor %}
          </h6>
          <h6>
              <a href="{% url 'webapp:issue_detail' issue.pk %}" class="card-link"><i class="fa fa-info-circle" aria-hidden="true"></i></a> <- details
              {% if request.user.is_authenticated %}
              <a href="{% url 'webapp:update_issue' issue.pk %}" class="card-link"><i class="fa-solid fa-pen-to-square"></i></a>
              <a href="{% url 'webapp:delete_issue' issue.pk %}" class="card-link"><i class="fa-solid fa-trash"></i></a>
              {%endif%}
          </h6>
      </div>
    </div>
    <p></p>

issue_tracker/webapp/templates/partial/pagination.html
<ul class="pagination">
    {% if not page_obj.has_previous %}
        <li class="page-item disabled">
            <a class="page-link">Very beginning</a>
        </li>
        <li class="page-item disabled">
            <a class="page-link">Back</a>
        </li>
    {% else %}
        <li class="page-item">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page=1">Very Beginning</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Back</a>
        </li>
        <li class="page-item"><a class="page-link"
                                 href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        </li>
    {% endif %}

    <li class="page-item active" aria-current="page">
         <form method="get">
             {% if search %}<input type="hidden" name="search" value="{{ search }}">{% endif %}
            <input type="text" class="form-control" name="page" value="{{ page_obj.number }}">
        </form>
{#        <a class="page-link" href="#">{{ page_obj.number }}</a>#}
    </li>

    {% if not page_obj.has_next %}
        <li class="page-item disabled">
            <a class="page-link">Next</a>
        </li>

        <li class="page-item disabled">
            <a class="page-link">Very End</a>

        </li>
    {% else %}
        <li class="page-item"><a class="page-link"
                                 href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
        <li class="page-item">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>

        </li>
        <li class="page-item">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">Very End</a>

        </li>
    {% endif %}
</ul>

issue_tracker/webapp/templates/partial/project_card.html
<div class="card" style="width: 18rem;">
  <div class="card-body">
      <h5 class="card-title">{{ project.title }} </h5>
      <h6 class="card-subtitle mb-2 text-muted"><i>Start Date: </i> {{ project.start_date }}</h6>
      <h6 class="card-subtitle mb-2 text-muted"><i>End Date: </i> {{ project.end_date }}</h6>
      <p class="card-text">{{ project.description|linebreaks }}</p>
      {% if request.user.is_authenticated %}
          <a href="{% url 'webapp:update_project' project.pk %}" class="card-link"><i class="fa-solid fa-pen-to-square"></i></a>
          <a href="{% url 'webapp:delete_project' project.pk %}" class="card-link"><i class="fa-solid fa-trash"></i></a>
      {% endif %}
  </div>
</div>

issue_tracker/webapp/templates/partial/project_cards.html
 <div class="card" style="width: 18rem;">
      <div class="card-body">
          <h5 class="card-title">{{ project.title }} </h5>
          <h6 class="card-subtitle mb-2 text-muted"><i>Start Date: </i> {{ project.start_date }}</h6>
          <h6 class="card-subtitle mb-2 text-muted"><i>End Date: </i> {{ project.end_date }}</h6>
          <a href="{% url 'webapp:project_detail' project.pk %}" class="card-link"><i class="fa fa-info-circle" aria-hidden="true"></i></a> <- details
      </div>
    </div>
    <p></p>

issue_tracker/webapp/templates/partial/search.html
<form class="d-flex" action="" method="GET">
    {{ form.search }}
    <input type="submit" class="form-control me-2" type="search" placeholder="Search" aria-label="Search" value="Search">
    {% for error in form.search.errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
</form>